question_data = [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The Indie Game Development Studio Cing, developers of Hotel Dusk and Last Window, "
                              "went bankrupt on March 1st, 2010.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "The game &quot;Battlefield 1&quot; takes place during World War I.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                  "question": "Stephen Chbosky wrote the book &#039;The Perks of Being A Wallflower&#039;.",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Board Games", "type": "boolean", "difficulty": "easy",
                  "question": "There is a Donald Trump Board Game, which was made in 1989.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "The Lego Group was founded in 1932.", "correct_answer": "True",
                  "incorrect_answers": ["False"]},
                 {"category": "General Knowledge", "type": "boolean", "difficulty": "easy",
                  "question": "Romanian belongs to the Romance language family, shared with French, Spanish, "
                              "Portuguese and Italian. ",
                  "correct_answer": "True", "incorrect_answers": ["False"]},
                 {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
                  "question": "Watch_Dogs 2 is a prequel.", "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Celebrities", "type": "boolean", "difficulty": "easy",
                  "question": "Tupac Shakur died due to complications from being stabbed in 1996.",
                  "correct_answer": "False", "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean", "difficulty": "easy",
                  "question": "In Chobits, Hideki found Chii in his apartment.", "correct_answer": "False",
                  "incorrect_answers": ["True"]},
                 {"category": "Entertainment: Books", "type": "boolean", "difficulty": "easy",
                  "question": "The Harry Potter series of books, combined, are over 1,000,000 words in length.",
                  "correct_answer": "True", "incorrect_answers": ["False"]}]
